version: '3'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    image: eureka-server
    ports:
      - 8761:8761
    networks:
      - watto
  user-service:
    container_name: user-service
    build:
      context: ../user-service
      dockerfile: Dockerfile
    image: user-service
    ports:
      - 8100:8100
    networks:
      - watto
    depends_on: 
      - eureka-server
    links:
      - eureka-server
  category-service:
    container_name: category-service
    build:
      context: ../category-service
      dockerfile: Dockerfile
    image: category-service
    ports:
      - 8200:8200
    networks:
      - watto
    depends_on: 
      - eureka-server
    links:
      - eureka-server
  item-service:
    container_name: item-service
    build:
      context: ../item-service
      dockerfile: Dockerfile
    image: item-service
    ports:
      - 8300:8300
    networks:
      - watto
    depends_on: 
      - eureka-server
    links:
      - eureka-server
  order-service:
    container_name: order-service
    build:
      context: ../order-service
      dockerfile: Dockerfile
    image: order-service
    ports:
      - 8400:8400
    networks:
      - watto
    depends_on: 
      - eureka-server
    links:
      - eureka-server
  api-gateway:
    container_name: api-gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: api-gateway
    ports:
      - 8080:8080
    networks:
      - watto
    links:
      - eureka-server
    depends_on: 
      - eureka-server
      - user-service
      - category-service
      - item-service
      - order-service
  watto-micro-frontend:
    container_name: watto-micro-frontend
    build:
      context: ../frontend
      dockerfile: dockerfile
    image: watto-micro-frontend
    ports:
      - 80:80
    networks:
      - watto
    depends_on: 
      - api-gateway
networks:
  watto:
    driver: bridge